- hosts: testservers
  become: true
  tasks:
 - name: Clone a github repository
     git:
       repo: https://github.com/ravikantchauhan/Linux_monitor.git
       dest: /home/
       clone: yes
       update: yes
  #tasks:
  - name: Installation
    shell: bash filesystem_usage.sh 2
