- hosts: testservers
  become: true
  tasks:
 - name: Clone a github repository
     git:
       repo: https://github.com/ravikantchauhan/Linux_monitor.git
       dest: /home/repos/
       clone: yes
       update: yes
  - name: Installation
    shell: bash system.sh 2
