- hosts: testservers
  become: true
 - name: Clone a github repository
     git:
       repo: https://github.com/ravikantchauhan/Linux_monitor.git
       dest: /home/repos/
       clone: yes
       update: yes
    tasks:
  - name: Installation
    shell: bash system.sh 2
